version: "3"

services:
  database:
    container_name: database
    image: mysql:8.3.0
    volumes:
      - "./database/database:/var/lib/mysql:rw"
      - "./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
      - "MYSQL_DATABASE=user"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=password"
    ports:
      - 3005:3005
    command: "mysqld --port=3005"

  web:
    container_name: web
    build: .
    depends_on:
      - database
    environment:
      - "DB_HOST=database"
      - "DB_PORT=3005"
      - "DB_DATABASE=user"
      - "DB_USER=user"
      - "DB_PASSWORD=password"
      - "PHP_PORT=3000"
      - "PHP_HOST=0.0.0.0"
      - "ACCOUNTS_SERVICE_URL=https://accounts.omelhorsite.pt"
      - "NOTIFICATIONS_API_KEY=123SECRETKEY321"
    ports:
      - 3000:3000
